Global data new
SpiNNakerManchester/SpiNNaker_PDP2 pull request #54
Opened 2022-03-17 07:54 UTC by Christian-B

Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/172

Simplified summary.

Most of the data has been moved from AbstractSimulatorBase to FecDataView

This means there is a lot less passing around of parameters and no need for injections.

Specifically for PdP2
the signature of generate_machine_data_specification has been simplified

Extra data needed can now be obtained directly on demand

This includes
FecDataView.get_routing_infos()
FecDataView.get_placements()
and a semantic sugar on placements
FecDataView.get_placement_of_vertex(vertex)

2022-03-17 08:01 UTC, lplana requested changes

2022-03-17 08:06 UTC, Christian-B commented
Thanks you!

Very good catch!
________________________________
From: Luis A. Plana ***@***.***>
Sent: 17 March 2022 08:02
To: SpiNNakerManchester/SpiNNaker_PDP2 ***@***.***>
Cc: Christian Brenninkmeijer ***@***.***>; Author ***@***.***>
Subject: Re: [SpiNNakerManchester/SpiNNaker_PDP2] Global data new (PR #54)


@lplana requested changes on this pull request.

________________________________

In spinn_pdp2/mlp_network.py<https://github.com/SpiNNakerManchester/SpiNNaker_PDP2/pull/54#discussion_r828840868>:

> @@ -666,7 +666,7 @@ def write_Lens_output_file (self,
                         gtv = g.t_vertex[s]
                         try:
                             rec_outputs[g.write_blk].append (gtv.read (
-                                gfe.placements().get_placement_of_vertex (gtv),
+                                FecDataView.get_placement_of_vertex(ftv),


This looks like a copy/paste bug. ftv should be gtv

________________________________

In spinn_pdp2/mlp_network.py<https://github.com/SpiNNakerManchester/SpiNNaker_PDP2/pull/54#discussion_r828841042>:

> @@ -801,7 +801,7 @@ def show_test_results (self):
             ltv = g.t_vertex[g.subgroups - 1]
             try:
                 rec_test_results = ltv.read (
-                    gfe.placements().get_placement_of_vertex (ltv),
+                    FecDataView.get_placement_of_vertex(ftv),


This looks like a copy/paste bug. ftv should be itv

—
Reply to this email directly, view it on GitHub<https://github.com/SpiNNakerManchester/SpiNNaker_PDP2/pull/54#pullrequestreview-912755597>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAEF4ZIBYAZDXQ7C5F73PD3VALRIHANCNFSM5Q6EQTHA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-03-17 08:18 UTC, Christian-B commented on spinn_pdp2/mlp_network.py
> +                                FecDataView.get_placement_of_vertex(ftv),
Agreed. fixed. Thanks

2022-03-17 08:20 UTC, Christian-B commented on spinn_pdp2/mlp_network.py
> +                    FecDataView.get_placement_of_vertex(ftv),
Agreed fixed. Thanks

2022-07-19 08:59 UTC, andrewgait approved these changes
This looks fine to me.

2022-07-21 16:24 UTC, merged